spring:
  datasource:
    url: jdbc:mysql://database-1.cpkm8ogi0egp.us-east-2.rds.amazonaws.com:3306/crypto?useSSL=false&serverTimezone=UTC
    username: admin
    password: Xixi1203

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: update
      show-sql: true

logging:
  level:
    org:
      hibernate:
        start: debug
        type: trace
    org.springframework.jdbc.core: DEBUG
    mybatis: DEBUG
    org.apache.ibatis: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.cryptoklineproject.model
  configuration:
    map-underscore-to-camel-case: true

binance:
  kline_api: /klines
  symbol_api: /exchangeInfo
  base_url: https://api.binance.us/api/v3
  limit: 500
  interval: 1m

app:
  kline:
    defaultNeed: 1440

redis:
  host: localhost
  port: 6379
  database: 0